#!/bin/bash
set -e

echo "=== HIDEYOU PRO — Настройка доменов ==="

# Get API URL from .env or default
source /root/hideyoupro/.env 2>/dev/null || true
API_BASE="http://localhost:4000"

# Get domain config from API (need auth token)
echo "Получаю настройки доменов из панели..."

# Read settings directly from DB instead of API (simpler, no auth needed)
PGPASSWORD=$POSTGRES_PASSWORD
LK_DOMAIN=$(docker exec hyp_postgres psql -U hideyoupro -d hideyoupro -t -c "SELECT value FROM settings WHERE key='lk_domain'" 2>/dev/null | tr -d ' \n')
WEBHOOK_DOMAIN=$(docker exec hyp_postgres psql -U hideyoupro -d hideyoupro -t -c "SELECT value FROM settings WHERE key='webhook_domain'" 2>/dev/null | tr -d ' \n')
MINIAPP_URL=$(docker exec hyp_postgres psql -U hideyoupro -d hideyoupro -t -c "SELECT value FROM settings WHERE key='miniapp_url'" 2>/dev/null | tr -d ' \n')

echo ""
echo "Домены из настроек:"
echo "  ЛК:      ${LK_DOMAIN:-не задан}"
echo "  Webhook:  ${WEBHOOK_DOMAIN:-не задан}"
echo "  MiniApp:  ${MINIAPP_URL:-не задан}"
echo ""

DOMAINS_TO_SETUP=()
[ -n "$LK_DOMAIN" ] && DOMAINS_TO_SETUP+=("$LK_DOMAIN")
[ -n "$WEBHOOK_DOMAIN" ] && DOMAINS_TO_SETUP+=("$WEBHOOK_DOMAIN")

if [ ${#DOMAINS_TO_SETUP[@]} -eq 0 ]; then
  echo "Нет доменов для настройки. Укажите домены в панели (Настройки → Личный кабинет)"
  exit 0
fi

# Get SSL certs
for DOMAIN in "${DOMAINS_TO_SETUP[@]}"; do
  echo "--- Настройка $DOMAIN ---"

  if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    echo "  SSL сертификат уже есть"
  else
    echo "  Получаю SSL сертификат..."
    # Stop nginx briefly for certbot standalone
    docker compose -f /root/hideyou/docker-compose.yml stop nginx 2>/dev/null || true
    certbot certonly --standalone -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email
    docker compose -f /root/hideyou/docker-compose.yml start nginx 2>/dev/null || true
    echo "  SSL сертификат получен"
  fi
done

# Generate nginx config
NGINX_CONF="/root/hideyou/nginx/conf.d/hideyoupro-domains.conf"
mkdir -p /root/hideyou/nginx/conf.d

cat > "$NGINX_CONF" << 'NGINX_EOF'
# === HIDEYOU PRO — Auto-generated domain config ===
# Generated by: bash /root/hideyoupro/scripts/setup-domains.sh
NGINX_EOF

for DOMAIN in "${DOMAINS_TO_SETUP[@]}"; do
  cat >> "$NGINX_CONF" << EOF

server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;

    location /api/ {
        proxy_pass http://hyp_backend:4000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /health {
        proxy_pass http://hyp_backend:4000;
    }

    location /_next/ {
        proxy_pass http://hyp_frontend:3000;
        proxy_http_version 1.1;
    }

    location / {
        proxy_pass http://hyp_frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
EOF
done

echo ""
echo "Nginx конфигурация создана: $NGINX_CONF"

# Reload nginx
docker compose -f /root/hideyou/docker-compose.yml restart nginx
echo ""
echo "=== Готово! ==="
echo ""
for DOMAIN in "${DOMAINS_TO_SETUP[@]}"; do
  echo "  https://$DOMAIN — настроен"
done
echo ""
echo "Проверьте доступность в браузере."
